### ISSUE TITLE
Add Yield Modal Error

### ISSUE THREAD

**Issue by ronaldj2008** [SwiftMike/hiigrade#41]
TypeError: Cannot read property 'substr' of undefined
YieldModal.render
src/components/modals/YieldModal.js:29
  26 | <Modal show={show}>
  27 |   <Modal.Header>
  28 |     <Modal.Title>
> 29 |       Group {this.props.selectedPlant.id.substr(0, 2)}
  30 |     </Modal.Title>
  31 |     <div>Strain Name: {this.props.selectedPlant.strain}</div>
  32 |   </Modal.Header>

**Comment by yoonslee** [comment]
@ronaldj2008 Hey ron, try pulling from my latest commits. I fixed alot of errors

**Comment by ronaldj2008** [comment]
![screen shot 2018-02-12 at 1 28 05 pm](https://user-images.githubusercontent.com/24511438/36120682-d25f9744-0ff8-11e8-9090-cae0986ec41f.png)

**Comment by yoonslee** [comment]
@ronaldj2008  I tried opening up the yield modal on my end, and am having no problems. Might be related to old plant instances on the database. Can you try creating another board first, and if that doesn't work, another user?

**Comment by yoonslee** [comment]
@ronaldj2008 Not having this error at all. Please open back up if it shows up again.
