### ISSUE TITLE
Plant Start Date on Plant Groups loss functionality  

### ISSUE THREAD

**Issue by ronaldj2008** [SwiftMike/hiigrade#42]

**Comment by yoonslee** [comment]
@ronaldj2008 This may be an issue with the old plant group instances on the database. Try creating a new user and a new board, and then creating new plant groups.

That should do the trick. If that doesn't work, let's hop on a Skype call and you can share your screen or something.

**Comment by yoonslee** [comment]
Still haven't had a chance to figure out how to backup the Mlabs before wiping. I don't think at this point it is as important as implementing features when we can just create new accounts with new plant groups.

**Comment by yoonslee** [comment]
Also, some additional info, for older plant groups on the database, they do not have the `planted_at` field, which I only added yesterday.

**Comment by yoonslee** [comment]
Only new ones might have that data field.

**Comment by yoonslee** [comment]
@ronaldj2008 Going to close this as it is working perfectly for me.

If there are any lingering issues, please feel free to open back up.
