### ISSUE TITLE
Destroy Function for Plant Group. Log Destroy 

### ISSUE THREAD

**Issue by ronaldj2008** [SwiftMike/hiigrade#43]

**Comment by yoonslee** [comment]
@ronaldj2008 Any thoughts on where the delete button should be, or would you like to leave that up to me? I'm thinking a trash icon of some sort could pop up when user hovers over a plant group. Or alternatively, we can put a delete button inside the View Plant Group modal.

Regardless, a confirmation modal is essential.

**Comment by yoonslee** [comment]
Added delete ability for plant groups (on mouse hover): 25b9f6843e1cae02e4e5b7eb22449641c0d799de
Added confirmation modal for deletion: 6b7aab6df0fc92ed7a26be77731e357e752618ca

**Comment by yoonslee** [comment]
@ronaldj2008 Got it to destroy plant and log an action.
