### ISSUE TITLE
Fix Landing Page Layout

### ISSUE THREAD

**Issue by ronaldj2008** [SwiftMike/hiigrade#48]

**Comment by yoonslee** [comment]
What specifically needs to get fixed? Please list out some fixes or some additional content to layout. In the meantime, I will center the bottom boxes. @ronaldj2008

**Comment by yoonslee** [comment]
Fixed centering of info boxes here: 721af87e66841756c0efba024c82eb47e2c08fdb

Also, made footer stick to very bottom of window.

If there's is anything else, let me know.

**Comment by ronaldj2008** [comment]
- The 3 text boxes as the bottom of the landing page are off center
- the icons are not rendering

**Comment by ronaldj2008** [comment]
Footer disappeared

**Comment by ronaldj2008** [comment]
Youre right. my browser view settings where too tight. when i zoomed out it looks fine. closing issue. thans
