### ISSUE TITLE
Add Landing Page email submission functionality 

### ISSUE THREAD

**Issue by ronaldj2008** [SwiftMike/hiigrade#49]

**Comment by yoonslee** [comment]
@ronaldj2008 Were you able to get the https://formspree.io/ to work? This is the quick plugin that I showed you, which can be inserted and used in a matter of minutes. I think this will be a good interim solution.

**Comment by ronaldj2008** [comment]
I haven't implemented it yet but I agree that we should use this solution.

**Comment by ronaldj2008** [comment]
So i tempted to use formspree.io and ran into a few problems. 

- I receive a message from formspree once email is submitted but the email value is blank. something seems to be blocking it
- Once the form is submitted it takes you off grolens.com. it would be better to have a simple confirmation modal appear

**Comment by yoonslee** [comment]
Done: fb769d0f406fa7f21b71101950bf4a57270eaf80
