### ISSUE TITLE
Fix Error Zone Add & Strain Add Error Messages

### ISSUE THREAD

**Issue by ronaldj2008** [SwiftMike/hiigrade#52]
When you try to do either of these actions it works but generate a weird error and the user has refresh or go back and start over

![Screen Shot 2018-02-13 at 6.31.20 PM.png](https://images.zenhubusercontent.com/58cb40f851aa2c305778b901/c07442d2-8115-4451-8310-a69d73d62d96)

![Screen Shot 2018-02-13 at 6.30.13 PM.png](https://images.zenhubusercontent.com/58cb40f851aa2c305778b901/8a6d12d4-bd2e-4dc0-bda1-d151eeb75d98)

**Comment by yoonslee** [comment]
Fixed here:
53f4a20a7b12062cd9496d959b639f98bf01c08e
