### ISSUE TITLE
Expense Modal Render Error 

### ISSUE THREAD

**Issue by ronaldj2008** [SwiftMike/hiigrade#58]
Also do we have a data model to persist expenses as well? This would be key

**Comment by ronaldj2008** [comment]
![screen shot 2018-02-15 at 8 58 40 am](https://user-images.githubusercontent.com/24511438/36273266-d2dacdf0-1238-11e8-853b-7d1407b0dd55.png)

**Comment by yoonslee** [comment]
Done: bbed8a70e77da136b948682bf9c817407db17469
